channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - click                # modular-type-along
  - conda
  - datrie               # needed as snakemake dependency sometimes
  - ipywidgets
  - jupyter
  - jupyterlab>2.1
  - jupyterlab-git
  - matplotlib
  #- nano                 # not built for windows
  - notebook
  - numpy
  - pandas
  - pycodestyle
  - pytest
  - python>3.7
  - seaborn
  - snakemake-minimal
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - jupyterlab-github
