name: base
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - conda
  - datrie               # needed as snakemake dependency sometimes
  - ipywidgets
  - jupyter
  - jupyterlab>2.1
  - matplotlib
  - nano                 # nano as an editor can't hurt
  - notebook
  - numpy
  - pandas
  - pycodestyle
  - pytest
  - python>3.7
  - seaborn
  - snakemake-minimal
  - sphinx
  - sphinx_rtd_theme

